### PR TITLE
export default kintoneUIComponent for JavaScript project

### PR DESCRIPTION
**Pull request by shuuji3**
Currently, in a JavaScript project using such as Webpack, we cannot import `kintoneUIComponent` as a whole. So we forced to import each component like this:

```js
import Button from 'kintoneUIComponent/lib/js/components/Button';
```
rather, we'd like to import

```js
import kintoneUIComponent from 'kintoneUIComponent/lib/js/components';
```
or
```js
import { Button } from 'kintoneUIComponent/lib/js/components';
```

This differentiates the usage of the minified version of JavaScirpt `kintone-ui-component.min.js`.

Ref. [QuickStart Javascript - kintone UI Component](https://kintone.github.io/kintone-ui-component/Getting-Started/QuickStart-Javascript/)

This PR enable to import in the latter ways.

### CODE REVIEW

**Comment by hokimcuc0202** [comment]
@shuuji3 
I see..
The old way to import seem very inconvenient and hard to use.
Thanks for pointing it out and improving it by new way.

I want to merge this pull but seem to have a conflict in dist/kintone-ui-component.min.js file.
Could you please help me resolve conflict in this pull to merge it?

**Comment by shuuji3** [comment]
@hokimcuc0202 Thanks for reviewing!
I've rebuilt `kintone-ui-component.min.js` to resolve the conflict.

**Comment by hokimcuc0202** [comment]
@shuuji3 
Thank you.
I have merged this pull request.

**Comment by shuuji3** [comment]
@hokimcuc0202 Thank you!

**Pull request merged**
